engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - src/**
exclude_paths:
- screeps-visual/
